import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Asset integrity.
 *
 * The GLBs are generated by Blender from tools/blender/, not committed by
 * hand, so the failure mode is not "someone edited a model wrong" — it is
 * "someone changed a script and nobody re-ran the pipeline", which produces a
 * game that loads a 404 and silently falls back to a grey box. These tests
 * make that loud.
 */

const MODELS = join(process.cwd(), 'public/assets/models');

/** Every asset the game actually asks for at runtime. */
const REQUIRED = [
  'dalida_bust.glb',
  'guimard_edicule.glb',
  'moulin_galette.glb',
  'wallace_fountain.glb',
  'street_lamp.glb',
  'morris_column.glb',
  'enemy_figure.glb',
  'weapon_handgun.glb',
  'weapon_machine_gun.glb',
  'weapon_shotgun.glb',
  'weapon_grenade.glb',
];

test('every required model exists', () => {
  for (const f of REQUIRED) {
    assert.ok(existsSync(join(MODELS, f)), `missing ${f} — run \`npm run assets\``);
  }
});

test('every model is a valid GLB', () => {
  for (const f of REQUIRED) {
    const buf = readFileSync(join(MODELS, f));
    // glTF binary header: magic "glTF", version, total length.
    assert.equal(buf.readUInt32LE(0), 0x46546C67, `${f} is not a GLB (bad magic)`);
    assert.equal(buf.readUInt32LE(4), 2, `${f} is not glTF 2.0`);
    assert.equal(buf.readUInt32LE(8), buf.length,
      `${f} header length disagrees with the file size — truncated export`);
  }
});

test('models are small enough to load up front', () => {
  for (const f of REQUIRED) {
    const size = readFileSync(join(MODELS, f)).length;
    assert.ok(size > 512, `${f} is suspiciously tiny (${size} B) — an empty export?`);
    assert.ok(size < 2_000_000, `${f} is ${Math.round(size / 1024)} KB; too big to preload`);
  }
});

test('the weapon set is complete and matches the weapon table', async () => {
  const { WEAPONS } = await import('../src/gameplay/weapons.js');
  for (const key of Object.keys(WEAPONS)) {
    const file = `weapon_${key.toLowerCase()}.glb`;
    assert.ok(existsSync(join(MODELS, file)),
      `${key} is in the weapon table but has no model (${file})`);
  }
});

test('the manifest lists what is actually on disk', () => {
  const manifestPath = join(MODELS, 'manifest.json');
  assert.ok(existsSync(manifestPath), 'the asset pipeline must write a manifest');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const onDisk = readdirSync(MODELS).filter((f) => f.endsWith('.glb')).sort();
  const listed = manifest.assets.map((a) => `${a}.glb`).sort();
  assert.deepEqual(listed, onDisk,
    'the manifest and the models directory disagree — re-run `npm run assets`');
});

test('the Blender palette matches the renderer palette exactly', async () => {
  // A colour changed in one place and not the other would quietly break the
  // amber/violet contract the whole look depends on, and would do it only for
  // the handful of objects that come from Blender — which is the hardest kind
  // of visual bug to notice.
  const py = readFileSync(join(process.cwd(), 'tools/blender/lib.py'), 'utf8');
  const js = readFileSync(join(process.cwd(), 'src/render/palette.js'), 'utf8');

  const pyColors = new Map();
  for (const m of py.matchAll(/"(\w+)":\s*"(#[0-9A-Fa-f]{6})"/g)) {
    pyColors.set(m[1], m[2].toUpperCase());
  }
  const jsColors = new Map();
  for (const m of js.matchAll(/(\w+):\s*c\('(#[0-9A-Fa-f]{6})'\)/g)) {
    jsColors.set(m[1], m[2].toUpperCase());
  }

  assert.ok(pyColors.size > 20, `only found ${pyColors.size} colours in lib.py`);
  const mismatches = [];
  for (const [name, hex] of pyColors) {
    const other = jsColors.get(name);
    if (other && other !== hex) mismatches.push(`${name}: blender ${hex} vs renderer ${other}`);
  }
  assert.deepEqual(mismatches, [],
    'Blender and the renderer disagree about these colours');
});
