import * as THREE from 'three';
import { PALETTE, flat } from '../render/palette.js';

/**
 * The ground: carriageway, pavements, kerbs and the two staircases.
 *
 * Everything here is generated by sampling the rail spline, so the street can
 * never drift away from the route the camera actually travels. Sampling is at
 * 1.5 m, which is fine enough that the rue d'Orchampt hairpin stays smooth and
 * coarse enough that the whole 654 m stays in one vertex budget.
 *
 * STAIRS. Montmartre is a staircase with a village on top, and two flights on
 * this route are load-bearing for recognition: the twin flight beside the
 * Lamarck-Caulaincourt métro mouth, and the long straight drop of the escalier
 * de la rue Ravignan. Both are modelled as real stepped geometry rather than a
 * ramp with a stair texture, because the camera climbs them and the tread
 * rhythm is visible in the parallax.
 */

const SAMPLE_M = 1.5;

/** Segments of the route that are stairs rather than roadway. */
export const STAIR_SEGMENTS = [
  { from: 'escalier_foot', to: 'escalier_top',  riser: 0.165, tread: 0.31, name: 'Escalier Lamarck' },
  { from: 'ravignan_stairs', to: 'trois_freres', riser: 0.155, tread: 0.33, name: 'Escalier Ravignan' },
];

/**
 * Build the full ground for a rail.
 * @param {import('../core/spline.js').Rail} rail
 */
export function buildStreet(rail) {
  const group = new THREE.Group();
  group.name = 'street';

  const n = Math.max(2, Math.floor(rail.length / SAMPLE_M));
  const frames = [];
  for (let i = 0; i <= n; i++) {
    const d = (i / n) * rail.length;
    const p = rail.positionAt(d);
    const t = rail.tangentAt(d);
    // Right-hand normal in the ground plane.
    const right = new THREE.Vector3(-t.z, 0, t.x).normalize();
    // The survey's `width` is BUILDING TO BUILDING, not kerb to kerb.
    //
    // Treating it as the carriageway and then adding 2.4 m of pavement on each
    // side inflated every street by nearly five metres: rue Girardon, which is
    // about nine metres wall to wall, was rendering at fourteen and reading as
    // a boulevard. That width is also what created the dead empty foreground
    // in every frame.
    //
    // Pavements narrow with the street, the way they really do — rue
    // d'Orchampt has barely a kerb, Place des Abbesses has a proper footway.
    const total = rail.widthAt(d);
    const pavement = Math.max(0.8, Math.min(2.4, total * 0.18));
    frames.push({
      d, p, t, right, pavement,
      halfWidth: Math.max(1.5, total * 0.5 - pavement),
    });
  }

  // The apron goes down FIRST so everything else sits on it.
  group.add(buildApron(frames));
  group.add(buildCarriageway(frames));
  // Pavements first: they compute the stepped walking surface that the kerbs
  // and the handrails both read back from.
  group.add(buildPavement(frames, +1));
  group.add(buildPavement(frames, -1));
  group.add(buildKerb(frames, +1));
  group.add(buildKerb(frames, -1));
  group.add(buildSlopeHandrails(frames));
  group.add(buildStairFlights(rail));

  return group;
}

/**
 * The ground the street sits on.
 *
 * Without this the road is a ribbon hanging in space. The distant plain is
 * thirty-eight metres below the route and starts a hundred and forty metres
 * out, and the Butte's flank cone tops out at the route's LOWEST elevation —
 * so everywhere the street climbs above that, there is a literal annular hole
 * between the edge of the pavement and the start of the world, and the camera
 * looks straight down into it. It is the single most damaging thing in any
 * frame that shows the lower half of the screen.
 *
 * The apron is a wide skirt following the rail at the street's own elevation,
 * falling away gently at its outer edge to meet the terrain. Generated from
 * the same frames as the carriageway, so it can never drift out of alignment
 * with the road it is supporting.
 */
function buildApron(frames) {
  const pos = [], idx = [];
  const REACH = 95;      // comfortably past the buildings and the alley walls
  const DROP = 7;        // how far the outer edge falls, so it reads as a hill
  const BANDS = [0, 0.16, 0.42, 1.0];

  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    for (const side of [-1, 1]) {
      for (const b of BANDS) {
        const off = side * (f.halfWidth + f.pavement + b * REACH);
        pos.push(
          f.p.x + f.right.x * off,
          f.p.y - 0.02 - DROP * b * b,
          f.p.z + f.right.z * off,
        );
      }
    }
  }
  const perRow = BANDS.length * 2;
  for (let i = 0; i < frames.length - 1; i++) {
    for (let side = 0; side < 2; side++) {
      const base = i * perRow + side * BANDS.length;
      const next = base + perRow;
      for (let b = 0; b < BANDS.length - 1; b++) {
        const a = base + b, c = a + 1, d = next + b, e = d + 1;
        if (side === 1) idx.push(a, d, c, c, d, e);
        else idx.push(a, c, d, c, e, d);
      }
    }
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setIndex(idx);
  g.computeVertexNormals();
  const mesh = new THREE.Mesh(g, flat(PALETTE.limestoneDeep, { roughness: 1.0 }));
  mesh.receiveShadow = true;
  mesh.name = 'apron';
  return mesh;
}

/** The cobbled roadway. Two-tone strips so the surface is not a dead plane. */
function buildCarriageway(frames) {
  const pos = [], idx = [], col = [];
  const warm = PALETTE.cobbleWarm, cool = PALETTE.cobbleCool;
  const STRIPS = 6;

  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    for (let s = 0; s <= STRIPS; s++) {
      const u = s / STRIPS - 0.5;
      const w = f.halfWidth * 2 * u;
      // Camber: Paris streets crown toward the centre and drain to the kerbs.
      const camber = -Math.abs(u) * Math.abs(u) * 0.22 + 0.055;
      pos.push(f.p.x + f.right.x * w, f.p.y + camber, f.p.z + f.right.z * w);
      const mix = ((i >> 1) + s) % 2 === 0 ? warm : cool;
      col.push(mix.r, mix.g, mix.b);
    }
  }
  const row = STRIPS + 1;
  for (let i = 0; i < frames.length - 1; i++) {
    for (let s = 0; s < STRIPS; s++) {
      const a = i * row + s, b = a + 1, c = a + row, d = c + 1;
      idx.push(a, c, b, b, c, d);
    }
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('color', new THREE.Float32BufferAttribute(col, 3));
  g.setIndex(idx);
  g.computeVertexNormals();
  const m = flat(0xffffff, { roughness: 0.95 });
  m.vertexColors = true;
  const mesh = new THREE.Mesh(g, m);
  mesh.receiveShadow = true;
  mesh.name = 'carriageway';
  return mesh;
}

/**
 * Raised pavement on one side. side = +1 right, -1 left.
 *
 * STEPPED, NOT RAMPED, and this is the single thing that makes the hill
 * visible.
 *
 * Over half of this route exceeds an 8% grade and it touches 23% on the climb
 * up Girardon — genuinely steep, and the three-act climb-crest-descend profile
 * is supposed to be the level's spine. It was invisible in every screenshot,
 * because a pavement that ramps smoothly alongside a road that ramps smoothly
 * gives the eye nothing to measure the slope against: both surfaces recede
 * together and the frame reads as flat ground seen in perspective.
 *
 * Paris solves this in the street itself. Above roughly 8% the pavement stops
 * following the road and becomes a flight of long shallow steps — it holds
 * level for several metres, drops a riser, holds level again. The consequence
 * is that the KERB FACE breathes: tall immediately after a step, shrinking to
 * nothing just before the next one. That rising and falling band of shadow
 * running up the street is what tells you, instantly and without thinking
 * about it, that you are looking at a hill.
 *
 * The stepping needs no gradient threshold. It snaps whenever the ramp has
 * drifted more than three quarters of a riser from the current tread, so a
 * gentle slope simply produces very long treads and a flat street produces
 * none at all.
 */
function buildPavement(frames, side) {
  const pos = [], idx = [];
  const HEIGHT = 0.16;
  const RISER = 0.15;

  let stepY = frames[0].p.y + HEIGHT;
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    const target = f.p.y + HEIGHT;
    let guard = 0;
    while (target - stepY > RISER * 0.75 && guard++ < 40) stepY += RISER;
    guard = 0;
    while (stepY - target > RISER * 0.75 && guard++ < 40) stepY -= RISER;
    // Record it so the kerb and the handrail agree with the pavement exactly.
    f.walkY = f.walkY ?? {};
    f.walkY[side] = stepY;

    const inner = f.halfWidth * side;
    const outer = (f.halfWidth + f.pavement) * side;
    pos.push(f.p.x + f.right.x * inner, stepY, f.p.z + f.right.z * inner);
    pos.push(f.p.x + f.right.x * outer, stepY, f.p.z + f.right.z * outer);
  }
  for (let i = 0; i < frames.length - 1; i++) {
    const a = i * 2, b = a + 1, c = a + 2, d = a + 3;
    if (side > 0) idx.push(a, c, b, b, c, d);
    else idx.push(a, b, c, b, d, c);
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setIndex(idx);
  g.computeVertexNormals();
  const mesh = new THREE.Mesh(g, flat(PALETTE.pavement, { roughness: 0.93 }));
  mesh.receiveShadow = true;
  mesh.name = `pavement${side > 0 ? 'R' : 'L'}`;
  return mesh;
}

/**
 * The kerb face — a thin vertical strip catching the low sun.
 *
 * Its top follows the STEPPED pavement and its bottom follows the ramped road,
 * so on a slope the face grows and shrinks between steps instead of holding a
 * constant 16 cm. That varying band is the slope cue; see buildPavement.
 */
function buildKerb(frames, side) {
  const pos = [], idx = [];
  const MIN = 0.1;
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    const x = f.halfWidth * side;
    const top = Math.max(f.p.y + MIN, f.walkY?.[side] ?? f.p.y + 0.16);
    pos.push(f.p.x + f.right.x * x, f.p.y, f.p.z + f.right.z * x);
    pos.push(f.p.x + f.right.x * x, top, f.p.z + f.right.z * x);
  }
  for (let i = 0; i < frames.length - 1; i++) {
    const a = i * 2, b = a + 1, c = a + 2, d = a + 3;
    if (side > 0) idx.push(a, b, c, b, d, c);
    else idx.push(a, c, b, b, c, d);
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setIndex(idx);
  g.computeVertexNormals();
  const mesh = new THREE.Mesh(g, flat(PALETTE.kerbStone, { roughness: 0.9 }));
  mesh.receiveShadow = true;
  return mesh;
}

/**
 * Real stepped geometry for the two flights.
 *
 * Step count is derived from the actual rise between the surveyed waypoints
 * divided by the riser height, so the flights have the number of steps the
 * elevation demands rather than a number someone typed.
 */
function buildStairFlights(rail) {
  const group = new THREE.Group();
  group.name = 'stairs';
  const mat = flat(PALETTE.stairStone, { roughness: 0.9 });

  for (const seg of STAIR_SEGMENTS) {
    let dA, dB;
    try {
      dA = rail.distanceToWaypoint(seg.from);
      dB = rail.distanceToWaypoint(seg.to);
    } catch { continue; }
    const lo = Math.min(dA, dB), hi = Math.max(dA, dB);
    const pA = rail.positionAt(lo), pB = rail.positionAt(hi);
    const rise = Math.abs(pB.y - pA.y);
    const steps = Math.max(4, Math.round(rise / seg.riser));
    const halfW = rail.widthAt((lo + hi) / 2) * 0.5;

    const flight = new THREE.Group();
    flight.name = seg.name;

    for (let i = 0; i < steps; i++) {
      const t0 = i / steps;
      const d = lo + (hi - lo) * t0;
      const p = rail.positionAt(d);
      const tan = rail.tangentAt(d);
      const right = new THREE.Vector3(-tan.z, 0, tan.x).normalize();

      const stepGeo = new THREE.BoxGeometry(halfW * 2, seg.riser, seg.tread * 1.02);
      const step = new THREE.Mesh(stepGeo, mat);
      step.position.copy(p);
      // Stack each tread up to the height the ramp would have had, so the
      // stepped surface averages onto the surveyed gradient exactly.
      step.position.y = THREE.MathUtils.lerp(pA.y, pB.y, t0) + seg.riser * 0.5;
      // Steps follow the street's yaw but stay level: a tread that tilts with
      // the gradient is a ramp with lines on it, not a stair.
      const levelTan = new THREE.Vector3(tan.x, 0, tan.z).normalize();
      step.lookAt(step.position.clone().add(levelTan));
      step.castShadow = true;
      step.receiveShadow = true;
      flight.add(step);

      void right;
    }

    // The central iron handrail. Both of these flights have one and it is the
    // detail that makes the staircase read as Montmartre rather than as steps.
    const railGeo = new THREE.BoxGeometry(0.07, 0.07, Math.abs(hi - lo));
    const railMesh = new THREE.Mesh(railGeo, flat(PALETTE.ironwork, { metalness: 0.4, roughness: 0.5 }));
    const mid = rail.positionAt((lo + hi) / 2);
    railMesh.position.copy(mid);
    railMesh.position.y = (pA.y + pB.y) / 2 + 0.95;
    // The handrail, by contrast, SHOULD follow the slope — that is what a
    // handrail does — so it keeps the full tangent.
    railMesh.lookAt(railMesh.position.clone().add(rail.tangentAt((lo + hi) / 2)));
    railMesh.castShadow = true;
    flight.add(railMesh);

    // Posts.
    const postCount = Math.max(2, Math.floor(Math.abs(hi - lo) / 2.5));
    for (let i = 0; i <= postCount; i++) {
      const t0 = i / postCount;
      const d = lo + (hi - lo) * t0;
      const p = rail.positionAt(d);
      const post = new THREE.Mesh(
        new THREE.BoxGeometry(0.06, 1.0, 0.06),
        flat(PALETTE.ironwork, { metalness: 0.4, roughness: 0.5 }),
      );
      post.position.set(p.x, THREE.MathUtils.lerp(pA.y, pB.y, t0) + 0.5, p.z);
      post.castShadow = true;
      flight.add(post);
    }

    group.add(flight);
  }
  return group;
}

/**
 * Iron handrails on the steepest pavements.
 *
 * Above roughly 14% Paris bolts a handrail along the kerb, and the Butte is
 * covered in them. They do two jobs here. The obvious one is that they are
 * true to the place. The useful one is that a handrail is a continuous line
 * that follows the slope exactly while its posts stay vertical, so it states
 * the gradient twice over — once with its own angle and once with the
 * lengthening posts underneath it. On a 23% climb that is unmistakable even
 * in a still frame.
 */
function buildSlopeHandrails(frames) {
  const group = new THREE.Group();
  group.name = 'handrails';
  const iron = flat(PALETTE.ironwork, { roughness: 0.5, metalness: 0.35 });
  const STEEP = 0.14;          // 14% grade
  const HEIGHT = 0.95;
  const POST_EVERY = 2.4;

  for (const side of [-1, 1]) {
    let run = null;
    const flush = () => {
      if (run && run.length >= 3) emitRun(group, run, side, iron, HEIGHT, POST_EVERY);
      run = null;
    };
    for (let i = 1; i < frames.length; i++) {
      const a = frames[i - 1], f = frames[i];
      const horiz = Math.hypot(f.p.x - a.p.x, f.p.z - a.p.z);
      const grade = horiz > 0.01 ? Math.abs(f.p.y - a.p.y) / horiz : 0;
      if (grade >= STEEP) {
        run ??= [];
        run.push(f);
      } else {
        flush();
      }
    }
    flush();
  }
  return group;
}

function emitRun(group, run, side, mat, height, postEvery) {
  // The rail itself: one segment per pair of frames, following the walking
  // surface rather than the road, so it sits at a constant height above the
  // steps a pedestrian is actually on.
  for (let i = 1; i < run.length; i++) {
    const a = run[i - 1], b = run[i];
    const ax = a.p.x + a.right.x * (a.halfWidth + a.pavement * 0.82) * side;
    const az = a.p.z + a.right.z * (a.halfWidth + a.pavement * 0.82) * side;
    const bx = b.p.x + b.right.x * (b.halfWidth + b.pavement * 0.82) * side;
    const bz = b.p.z + b.right.z * (b.halfWidth + b.pavement * 0.82) * side;
    const ay = (a.walkY?.[side] ?? a.p.y) + height;
    const by = (b.walkY?.[side] ?? b.p.y) + height;

    const len = Math.hypot(bx - ax, by - ay, bz - az);
    if (len < 0.05) continue;
    const seg = new THREE.Mesh(new THREE.BoxGeometry(0.055, 0.055, len), mat);
    seg.position.set((ax + bx) / 2, (ay + by) / 2, (az + bz) / 2);
    seg.lookAt(bx, by, bz);
    seg.castShadow = true;
    group.add(seg);
  }

  // Posts stay vertical while the rail above them climbs, which is the second
  // half of the slope cue — they visibly lengthen down the hill.
  let since = 999;
  for (const f of run) {
    since += 1.5;                       // frames are sampled every 1.5 m
    if (since < postEvery) continue;
    since = 0;
    const x = f.p.x + f.right.x * (f.halfWidth + f.pavement * 0.82) * side;
    const z = f.p.z + f.right.z * (f.halfWidth + f.pavement * 0.82) * side;
    const base = f.walkY?.[side] ?? f.p.y;
    const post = new THREE.Mesh(new THREE.BoxGeometry(0.05, height, 0.05), mat);
    post.position.set(x, base + height / 2, z);
    post.castShadow = true;
    group.add(post);
  }
}
